### ISSUE TITLE
#15 - Database

### ISSUE THREAD

**Issue by smoreno11** [DonovanFoley/CS1CProject2#14]
## Story: 15
	As a store manager I want to be have a database where I can store customers information/purchases and inventory items.

## Assumption:
	- The database can be created

## Tasks:
- [x] Store customer purchases into the database
- [x] Store the inventory of items into the database
- [x] Store customer information into the database 

## Story Estimation:
     3

## Done:
	- The admin can use an exterior tool like (DB Browser) to verify that the customer information 
        - and inventory has been inserted in the database. 

## Assignee:
	Saul
